import { DataTypes } from 'sequelize';
import sequelize from '../../config/connectionDB.js';

const PropertySocialDetailsHistory = sequelize.define(
  'propertysocialdetails_history',
  {
    HistoryID: {
      type: DataTypes.BIGINT,
      primaryKey: true,
      autoIncrement: true,
    },
    UpdVersionID: {
      type: DataTypes.STRING(100),
      allowNull: true
    },
    OwnerID: DataTypes.INTEGER,

    IsSolar: DataTypes.BOOLEAN,
    NoOfSolar: DataTypes.INTEGER,
    IsBoar: DataTypes.BOOLEAN,
    NoOfBoar: DataTypes.INTEGER,
    IsRainwaterharvesting: DataTypes.BOOLEAN,
    NoOfRainwaterharvesting: DataTypes.INTEGER,
    IsWaterConn: DataTypes.BOOLEAN,
    WaterConnSize: DataTypes.STRING(10),
    WaterConnectionYear: DataTypes.INTEGER,
    IsWaterMeter: DataTypes.BOOLEAN,
    TapUse: DataTypes.STRING(20),
    IsHandPump: DataTypes.BOOLEAN,
    NoOfHandPump: DataTypes.INTEGER,
    IsWell: DataTypes.BOOLEAN,
    NoOfWell: DataTypes.INTEGER,
    IsLift: DataTypes.BOOLEAN,
    NoOfLift: DataTypes.INTEGER,
    RoadNo: DataTypes.STRING(10),
    RoadWidth: DataTypes.INTEGER,
    IsGarbageSegrigation: DataTypes.BOOLEAN,
    ISGarbageDisposal: DataTypes.BOOLEAN,
    IsSepticTank: DataTypes.BOOLEAN,
    NoOfSepticTank: DataTypes.INTEGER,
    IsEBill: DataTypes.BOOLEAN,
    NoOfTrees: DataTypes.INTEGER,
    DirectionEast: DataTypes.STRING(50),
    DirectionWest: DataTypes.STRING(50),
    DirectionNorth: DataTypes.STRING(50),
    DirectionSouth: DataTypes.STRING(50),

    NoOfWaterConnection: DataTypes.INTEGER,
    WaterConnectionType: DataTypes.STRING(50),
    MeterStatus: DataTypes.STRING(50),
    WaterBillAreaName: DataTypes.STRING(100),
    WaterBillConnectionNo1: DataTypes.INTEGER,
    WaterBillMeterNo: DataTypes.INTEGER,
    ConnectionNo2: DataTypes.INTEGER,
    MeterNo2: DataTypes.INTEGER,
    ConnectionNo3: DataTypes.INTEGER,
    MeterNo3: DataTypes.INTEGER,
    ConnectionNo4: DataTypes.INTEGER,
    MeterNo4: DataTypes.INTEGER,
    ConnectionNo5: DataTypes.INTEGER,
    MeterNo5: DataTypes.INTEGER,
    IsTubeWell: DataTypes.BOOLEAN,
    ToiletSeatCountResidential: DataTypes.INTEGER,
    ToiletSeatCountNonResidential: DataTypes.INTEGER,
    IsWastewaterOutlet: DataTypes.BOOLEAN,
    IsEtpStp: DataTypes.BOOLEAN,
    IsHomeComposting: DataTypes.BOOLEAN,
    IsVermicompost: DataTypes.BOOLEAN,
    IsECharging: DataTypes.BOOLEAN,
    IsUndergroundSewage: DataTypes.BOOLEAN,
    IsUndergroundTank: DataTypes.BOOLEAN,
    IsBoosterPump: DataTypes.BOOLEAN,
    WaterBillCustomerNo: DataTypes.INTEGER,
    IsFireSafety: DataTypes.BOOLEAN,
    NoOfFireSafety: DataTypes.INTEGER,
    IsBuildingPermission: DataTypes.BOOLEAN,
    IsOcIssued: DataTypes.BOOLEAN,
    OcNo: DataTypes.INTEGER,
    WaterRemark: DataTypes.STRING(255),
    ParkingRemark: DataTypes.STRING(255),
    BorewellRemark: DataTypes.STRING(255),
    CCNumber: DataTypes.INTEGER,

    SnapshotType: DataTypes.STRING(10),
    UserID: DataTypes.INTEGER,
    SnapshotCreatedAt: DataTypes.DATE,
  },
  {
    tableName: 'propertysocialdetails_history',
    timestamps: false,
  }
);

export default PropertySocialDetailsHistory;
