export const TOOL_FRONTEND_URL = "/";
 export const TOOL_API_URL = "/webapi";
 
export const API_URLS = {
  POST: {
    SIGN_UP: "/signup",
    SIGN_IN: "/auth/login",
    RESET_PASSWORD: "/reset_password",
    GET_OTP: "/otp",
    ADD_USER_DATA: "/users",
    SAVE_BASIC_DETAILS: "basic",
    SAVE_COVER_DETAILS: "cover",
    SAVE_TENDER_FEE_DETAILS: "tender_fee",
    SAVE_EMD_FEE_DETAILS: "emd_fee",
    SAVE_WORK_ITEM_DETAILS: "work_item",
    SAVE_CRITICAL_DATES: "critical_dates",
    SAVE_STAMP_DETAILS: "stamp",
    SAVE_ELIGIBILITY_DETAILS: "eligibility",
    SAVE_ADDITIONAL_DETAILS: "additional",
    SAVE_DOCS_DETAILS: "documents",
    SAVE_DA_DOCS_DETAILS: "da_documents",
    SAVE_FA_APPROVAL: "finance_approval",
    SAVE_TL_AUTHORIZE: "tl_authorize",
    SAVE_GOV_SELECTION: "save_tender_selection",
    SAVE_LZERO_DETAILS: "lzero_approval",
    DA_DOC_UPLOAD: "da_doc_upload",
    DA_DOC_SUBMISSION: "phy_doc_submission",
    SAVE_L1_APPROVAL_DETAILS: "l1_approval_details",
    SAVE_PHY_TRACKING_SETUP: "physical_tracking_setup",
    SAVE_PHY_TRACKING_PROGRESS: "physical_tracking_progress",
    SAVE_FIN_TRACKING_PROGRESS: "financial_tracking_progress",
    SAVE_FIN_CLOSURE: "financial_closure",
    SAVE_FINAL_CLOSURE: "final_closure",
    SAVE_CORRIGENDUM: "save_corrigendum",
    SAVE_EXPENSE: "save_expense",
    SUBMIT_TENDER: "submit",
    UPLOAD_DOCS: "/files",
    SUBMIT_TENDER_ACTION_API: "tenders/submit_tender_action",
    SUBMIT_EXPENSE_ACTION_API: "tenders/submit_expense_action",
  },
  GET: {
    GET_USER_DATA_LIST: "/users",
    GET_ALL_USER_LIST: "/users/userIds",
    GET_BASIC_DETAILS: 'basic',
    GET_COVER_DETAILS: 'cover',
    GET_TENDER_FEE_DETAILS: 'tender_fee',
    GET_EMD_FEE_DETAILS: 'emd_fee',
    GET_WORK_ITEM_DETAILS: 'work_item',
    GET_CRITICAL_DATES: 'critical_dates',
    GET_STAMP_DETAILS: 'stamp',
    GET_ELIGIBILITY_DETAILS: 'eligibility',
    GET_ADDITIONAL_DETAILS: 'additional',
    GET_TENDER_APPROVAL_DETAILS: 'approval_details',
    GET_DA_UPLOADED_DOCS: "da_uploaded_docs",
    GET_DOCS_DETAILS: 'documents',
    GET_DA_DOCS_DETAILS: 'da_documents',
    GET_DA_DOC_SUBMITTED_DETAILS: 'da_doc_submitted',
    GET_PHY_TRACKING_DETAILS: 'physical_tracking_details',
    GET_FIN_TRACKING_DETAILS: 'financial_tracking_details',
    GET_SELECTION_DETAILS: 'tender_selection_details',
    GET_L0_ACCEPTANCE_DETAILS: 'l0_acceptance_details',
    GET_L1_APPROVAL_DETAILS: 'l1_approval_details',
    GET_FIN_CLOSURE_DETAILS: 'financial_closure_details',
    GET_FINAL_CLOSURE_DETAILS: 'final_closure_details',
    GET_TENDER_STATUS: 'get_tender_status',
    GET_EXPENSE_DATA: 'expense_details',
    DOWNLOAD_DOCS: '/files',
    GET_DEPARTMENT_LIST: '/departments',
    GET_SEARCH_FILTERS: '/tenders/get_search_filters',
    GET_EXPENSE_SEARCH_FILTERS: '/tenders/get_expense_search_filters',
    GET_TENDER_LIST: '/tenders',
    GET_CORRIGENDUM_LIST: '/tenders/corrigendum_list',
    GET_EXPENSE_LIST: '/tenders/expense_list',
    GET_EXPENSE_TYPE_LIST: '/tenders/expense_type_list',
    GET_WORK_LIST_COUNT: '/tenders/work_list_count',
    GET_WORK_LIST_EXPENSE_COUNT: '/tenders/work_list_expense_count',
    GET_DEPARTMENT_AGG_EXP_REPORT: '/report/departmentAggregatedExpenseReport',
    GET_TENDER_AGG_EXP_REPORT: '/report/tenderAggregatedExpenseReport',
    GET_TENDER_EXP_REPORT: '/report/tenderexpensereport',
    GET_TENDER_MONITOR_REPORT: '/report/tendermonitoringreport',
  },
  PUT: {
    UPDATE_USER_DATA: "/users"
  },
  DELETE: {
    DELETE_USER_DATA: "/users"
  }
};

