import AssessmentRulesMaster from '../../models/models/assessmentrulesmaster.js';
import PropertyMast from '../../models/models/propertymast.js';
import AssessmentMaster from '../../models/models/assessmentmaster.js';
import { getAssessmentIdForOwner } from '../master/applyTaxController.js';



const convertToBoolean = (value) => value === true;

// Add assessment rules to the assessment rule master database.
export const addAssessmentRules = async (req, res) => {
  const {
    minRV,
    minRvOldRvZero,
    asPerOldForNewProperty,
    appealPolicyRuleWise,
    asPerOld,
    mixassessment,
    policyApplicable,
    retention,
    isRetention,
    capitalValue,
    historyLock,
    utilityLock,
    applyDiscount,
    dataEntryLock,
    drainTaxFlat,
    postingDeleted,
    newPropertyRemark,
    appealMaxDisc,
    lockPropertyEditional,
    showPhotosAndPlan,
    minusPendingTax,
    photoPlanDB,
    restrictWrongFloor,
    restrictDuplicateEntry,
    plotTaxable,
    isHearing,
    plotTaxApplicable,
    isReasonLock,
    calfloorRenterRent,
    calcombineRenterRent,
    isAppealCommity,
    opEduEmpTax,
    isRemission,
    Deviation,
    dataEntryScreen,
    meter,
    invoiceAutoGnerated,
    pendingDemandPay,
    reportImagePath,
    discountOnInterestBill,
    otpEnabled,
    wardAllocation,
    applyDiscountforExtended,
    ownerIdForReportName,
    rentValidity,
    qrCode,
    receiptPrint,
    hearingMaxDisc,
    currentBalance,
    pendingBalance,
    activeInterest2,
    dbForAMC,
    assesmentCompleted,
    allowSMS,
    policyLock,
    dukanGalaMaintenance,
    penaltyMonthly,
  } = req.body;

  console.log(req.body, 'requested body');

  try {
    // Delete all existing assessment rules
    await AssessmentRulesMaster.destroy({
      where: {},
    });
    console.log('Deleted all existing assessment rules');

    // Create the new assessment rules in the database
    const assessmentRules = await AssessmentRulesMaster.create({
      AssessmentID: await getAssessmentIdForOwner(),
      IsMinimumRV: convertToBoolean(minRV),
      IsMinimumRVForOldRVZero: convertToBoolean(minRvOldRvZero),
      IsAsPerOldForNewProperty: convertToBoolean(asPerOldForNewProperty),
      IsAppealPolicyRuleWise: convertToBoolean(appealPolicyRuleWise),
      IsAsPerOld: convertToBoolean(asPerOld),
      IsMixAssessment: convertToBoolean(mixassessment),
      IsPolicyApplicable: convertToBoolean(policyApplicable),
      IsRetention: convertToBoolean(retention),
      IsRetaintion: convertToBoolean(isRetention),
      iscv: convertToBoolean(capitalValue),
      AddHistoryLock: convertToBoolean(historyLock),
      UtilityLockInBuiltUpArea: convertToBoolean(utilityLock),
      IsApplyDiscount: convertToBoolean(applyDiscount),
      DataEntryLock: convertToBoolean(dataEntryLock),
      IsApplyFlatRateDrain: convertToBoolean(drainTaxFlat),
      isBillTransactionEntryDeleted: convertToBoolean(postingDeleted),
      IsDisplayNewPropRemark: convertToBoolean(newPropertyRemark),
      AppealMaxDiscount: appealMaxDisc,
      AvoidPropertyEditing: convertToBoolean(lockPropertyEditional),
      isShowPlansAndPhoto: convertToBoolean(showPhotosAndPlan),
      AcceptMinusPendingTaxes: convertToBoolean(minusPendingTax),
      isPhotoPlanFromDb: convertToBoolean(photoPlanDB),
      IsWrongFloorSequence: convertToBoolean(restrictWrongFloor),
      isDuplicateEntryRestricted: convertToBoolean(restrictDuplicateEntry),
      IsPlotTaxable: convertToBoolean(plotTaxable),
      IsHearing: convertToBoolean(isHearing),
      IsPlotTaxApplicable: convertToBoolean(plotTaxApplicable),
      IsReasonLock: convertToBoolean(isReasonLock),
      IsCalOnRenterRent: convertToBoolean(calfloorRenterRent),
      IsCalOnSingleRenterRent: convertToBoolean(calcombineRenterRent),
      IsAppealCommittee: convertToBoolean(isAppealCommity),
      IsOPEduEmpTaxZeroForGovEduProp: convertToBoolean(opEduEmpTax),
      IsRemission: convertToBoolean(isRemission),
      Daviation: Deviation,
      IsSubOnDataEntry: convertToBoolean(dataEntryScreen),
      IsSubOnMeter: convertToBoolean(meter),
      IsInvoiceAutoGenerated: convertToBoolean(invoiceAutoGnerated),
      IsPendingDemandPayFirst: convertToBoolean(pendingDemandPay),
      IsReportImageFromPath: convertToBoolean(reportImagePath),
      IsDiscountOnIntNMbuild: convertToBoolean(discountOnInterestBill),
      IsOTPEnable: convertToBoolean(otpEnabled),
      IsWardAllocation: convertToBoolean(wardAllocation),
      IsApplyDiscountForExtended: convertToBoolean(applyDiscountforExtended),
      IsSpecificFormatReportSaveByOwnerID:
        convertToBoolean(ownerIdForReportName),
      IsRentValidity: convertToBoolean(rentValidity),
      IsQRcode: convertToBoolean(qrCode),
      IsReceiptPrint: convertToBoolean(receiptPrint),
      HearingMaxDiscount: hearingMaxDisc,
      CurrentBalance: convertToBoolean(currentBalance),
      PendingBalance: convertToBoolean(pendingBalance),
      IsActiveInterest2: convertToBoolean(activeInterest2),
      isDBForAMC: convertToBoolean(dbForAMC),
      isAssessmentCompleted: convertToBoolean(assesmentCompleted),
      IsAllowSMS: convertToBoolean(allowSMS),
      PolicyLock: convertToBoolean(policyLock),
      IsMaintainanceApply: convertToBoolean(dukanGalaMaintenance),
      IsPenaltyMonthaly: convertToBoolean(penaltyMonthly),
  
      CreatedDate: new Date(),
    });

    res.status(200).json({
      message: 'Assessment rules applied successfully',
      assessmentRules,
    });
    console.log('Assessment rules saved:', assessmentRules);
  } catch (error) {
    console.error('Error in adding rules:', error);
    res.status(500).json({
      error: 'An error occurred while adding rules.',
    });
  }
};

export const getAssessmentRules = async (req, res) => {
  try {
    const getAssessmentInfo = await AssessmentRulesMaster.findOne({
      attributes: [
        'ID',
        'AssessmentID',
        'MaintenanceRate',
        'DataEntryLock',
        'AddHistoryLock',
        'IsAsPerOld',
        'IsAsPerOldForNewProperty',
        'IsMinimumRV',
        'IsMinimumRVForOldRVZero',
        'IsMixAssessment',
        'IsRetaintion',
        'IsCalOnRenterRent',
        'IsAppealPolicyRuleWise',
        'IsPlotTaxApplicable',
        'IsPlotTaxable',
        'IsTypeOfUseGroup',
        'IsPolicyApplicable',
        'PolicyLock',
        'UtilityLockInBuiltUpArea',
        'IsCalOnSingleRenterRent',
        'HearingMaxDiscount',
        'AppealMaxDiscount',
        'isDuplicateEntryRestricted',
        'IsRetention',
        'IsHearing',
        'IsAppealCommittee',
        'IsRemission',
        'IsReasonLock',
        'IsSpecificFormatReportSaveByOwnerID',
        'isShowPlansAndPhoto',
        'AvoidPropertyEditing',
        'IsReportImageFromPath',
        'iscv',
        'IsApplyFlatRateDrain',
        'AcceptMinusPendingTaxes',
        'IsOPEduEmpTaxZeroForGovEduProp',
        'IsApplyDiscount',
        'isPhotoPlanFromDb',
        'Daviation',
        'CurrentBalance',
        'PendingBalance',
        'IsDisplayNewPropRemark',
        'IsReceiptPrint',
        'IsWardAllocation',
        'IsApplyDiscountForExtended',
        'IsAddInterestToSelectedYear',
        'IsRentValidity',
        'IsActiveInterest2',
        'IsMaintainanceApply',
        'isDBForAMC',
        'isAssessmentCompleted',
        'AddTaxesRemark',
        'IsAllPropertyChangedForAddTaxes',
        'isBillTransactionEntryDeleted',
        'IsTaxOnToilet',
        'IsDiscountOnIntNMbuild',
        'IsInvoiceAutoGenerated',
        'IsPendingDemandPayFirst',
        'IsAllowSMS',
        'IsOTPForCounterLogin',
        'IsApprovalByCouncil',
        'IsSubOnDataEntry',
        'IsSubOnMeter',
        'IsApprovalDocument',
        'IsDuplicateAvoid',
        'IsPrintDuplicate',
        'IsOTPEnable',
        'IsQRcode',
        'IsOPEduEmpIsTaxZeroForGovEduProp',
        'IsPenaltyMonthaly',
        'IsWrongFloorSequence',
        'IsBuildUpArea',
        'IsCarpetArea',
        'CreatedBy',
        'CreatedDate',
        'UpdatedBy',
        'UpdatedDate',
      ],
    });
    res.status(200).json(getAssessmentInfo);
  } catch (error) {
    res.status(500).json({
      error: 'An error occurred while getting Assessment Info.',
    });
  }
};

export const saveNpprefix = async (req, res) => {
  try {
    // Fetch the NPPrefix from AssessmentMaster
    const assessmentMaster = await AssessmentMaster.findOne({
      attributes: [['NPPrefix', 'prefixNo']],
    });

    // Log the result for debugging purposes
    console.log('AssessmentMaster:', assessmentMaster);

    if (!assessmentMaster) {
      throw new Error('AssessmentMaster record not found');
    }

    // Retrieve the prefix number from the fetched record
    const prefixNo = assessmentMaster.get('prefixNo');
    console.log('prefixNo:', prefixNo);

    if (!prefixNo) {
      throw new Error('Prefix number not found in AssessmentMaster record');
    }

    // Fetch all the records from PropertyMast
    const propertyInfo = await PropertyMast.findAll({
      attributes: ['OwnerID'],
    });

    // Log propertyInfo for debugging
    console.log('PropertyMast Records:', propertyInfo);

    // Update each record in PropertyMast with the new AssessmentNo
    for (let index = 0; index < propertyInfo.length; index++) {
      const ownerID = propertyInfo[index].OwnerID;

      // Generate new assessment no with index number
      const newAssessmentNo = prefixNo + `${index + 1}`;

      console.log(
        `Updating OwnerID: ${ownerID} with AssessmentNo: ${newAssessmentNo}`
      );

      await PropertyMast.update(
        {
          AssessmentNo: newAssessmentNo,
        },
        { where: { OwnerID: ownerID } }
      );
    }

    res.status(200).json('Assessment number generated successfully');
  } catch (error) {
    console.error('Error:', error);
    res.status(500).json({ error: error.message });
  }
};
