const reportNames = [
  'Missing Photo List',
  'Missing Plan Plan',
  'Zero Tax Property List',
  'Default Property List',
  'Holder List',
  'Missing Property Details List',
  'Old Tax Greater Old Rv List',
  'Old Property Tax Greater Old Tax',
  'Old Property Without Old Tax and Old RV',
  'Construction Type and Tax Wise List',
  'Property With Current Appeal Status List',
  'Properties in Auto Hearing List',
  'Properties in Auto Appeal Committee List',
  'Properties with missing floor Details',
  'Properties having zero carpet area',
  'Auto AC List',
  'Combine Property List',
  'Toilet Count',
  'Properties without rent',
  'Properties without old Property tax and old total tax',
  'Missing Address,Address in Marathi and Mobile No ',
  'Missing Toilet',
  'Duplicate Property List',
  'Duplicate Floor List',
  'Old RV has value but Net tax is Zero',
  'Properties without Renter',
  'Missing Invoice No.',
  'Missing floor information in property and execluding plots',
  'Missing New and Old Floor type of use information',
  'Properties with renter and having rent',
  'Missing Appeal Policy With compare to Actual Table values',
  'Canceled Invoice Lists',
  'Open Plot Properties',
  'Transaction Report',
  'Advance Payment Transaction Report',
  'Bill Book LIst',
  'Oblique Property List',
  'Comparision of Old and new Rv in parentage',
  'Under Construction Properties',
  'Property Data',
  'Property Description Mismatch Property',
  'Bank,Tower ,Office,Hostels without Rent',
  'Total Tax in Between Given Range',
  'Total Tax is greater than 100000',
  'Properties having old property no but its old Tax and Old RV is zero',
  'Properties have old Tax but Net Tax is Zero',
  'Missing Plot Area list',
  'Zero Tax Open Plot',
  'Missing ShopName List',
  'Missing GIS Photo List',
  'Property Description',
  'New TOtalTax is 10 times greater than Old TotalTax',
  'New TOtalTax is 3 times less than Old TotalTax',
  'totalTax is less than old total tax',
  'Comparision',
  'Residential properties to which employment tax is applied',
  'Commercial properties to which employment tax is not applied',
  'New Properties',
  'Outer Properties',
  'Old Tax is greater than Old RV',
  'Properties having new Rv but Net Tax is zero',
  'Missing Property No',
  'Data Entry Gap',
  'Utility Mistmatch Properties.',
  'Comparision Report',
  'Tax is applied but Tax value is zero',
  'Mutation List',
  'Property Chart',
  'Zoning List',
  'Property is non taxtable but Total Tax is Greater than Zero',
  'Propert is TaxTable but Total Tax is Zero',
  'Old carpert area not matching in flat system.',
  'Old RV not matching in flat system',
  'Old Property Tax not matching in flat system',
  'Old Total Tax not matching in flat system',
  'New carpert area not matching in flat system.',
  'Toilet count not matching in flat system',
  'PLot area is not matching in flat system',
  'Property Description not matching in old flat system.',
  'Construction type not matching in old flat system.',
  'Construction year not matching in old flat system.',
  'Tax is not matching in flat system',
  'Second photo is misssing in old flat system.',
  'Apartment name not matching in old flat system.',
  'Shop name is not matching in old flat system.',
  'Zone not matching in flat system.',
  "Construction Type like 'AR','BR','CR'..etc but Calculated Rent is zero",
  'Old Total Tax/Old prop Tax greater than Old RV.',
  'Residential properties but education tax is not applied.',
  'Commercial properties but education tax is not applied.',
  'Comparision of Rooms with Respect to Carpet Area',
  'Comparision of toilet with Respect to Carpet Area'
];

export const QCList = Array.from({ length: reportNames.length }, (_, index) => ({
  id: index + 1,
  name: `${index + 1})${reportNames[index]}`
}));
